function [normalLoad, longitudinalAcceleration] = ...
    load_transfer(dynamicLongitudinalForce, vehicleSpeed, lateralAcceleration, params)

    dynamicLongitudinalForce = dynamicLongitudinalForce(:).';

    aerodynamicDrag = 0.5 * params.airDensity * params.dragCoefficient * ...
        params.frontalArea * vehicleSpeed.^2;
    rollingResistance = params.rollingResistanceCoefficient * ...
        params.vehicleMass * params.gravity;

    totalLongitudinalForce = ...
        dynamicLongitudinalForce(1) + dynamicLongitudinalForce(2) + ...
        dynamicLongitudinalForce(3) + dynamicLongitudinalForce(4);

    longitudinalAcceleration = ...
        (totalLongitudinalForce - aerodynamicDrag - rollingResistance) / params.vehicleMass;

    vehicleWeight = params.vehicleMass * params.gravity;
    aeroDownforce = 0.5 * params.airDensity * params.downforceCoefficient * ...
        params.frontalArea * vehicleSpeed.^2;

    frontAxleLoad = vehicleWeight * (params.rearAxleToCg / params.wheelbase) + ...
        aeroDownforce * (1 - params.rearDownforceFraction);
    rearAxleLoad = vehicleWeight * (params.frontAxleToCg / params.wheelbase) + ...
        aeroDownforce * params.rearDownforceFraction;

    longitudinalLoadTransfer = params.vehicleMass * longitudinalAcceleration * ...
        params.centerOfGravityHeight / params.wheelbase;
    frontAxleLoad = frontAxleLoad - longitudinalLoadTransfer;
    rearAxleLoad = rearAxleLoad + longitudinalLoadTransfer;

    frontLateralLoadTransfer = (frontAxleLoad / params.gravity) * lateralAcceleration * ...
        params.centerOfGravityHeight / params.trackWidth;
    rearLateralLoadTransfer = (rearAxleLoad / params.gravity) * lateralAcceleration * ...
        params.centerOfGravityHeight / params.trackWidth;

    normalLoad = [
        frontAxleLoad/2 - frontLateralLoadTransfer, ...
        frontAxleLoad/2 + frontLateralLoadTransfer, ...
        rearAxleLoad/2 - rearLateralLoadTransfer, ...
        rearAxleLoad/2 + rearLateralLoadTransfer
    ];
    normalLoad = max(normalLoad, 0);
end
