function [commandedMotorTorque, integralStateRate, slipError, ...
    gainSchedule, feedforwardTorque] = tc_control(slipRatio, integralState, ...
    vehicleSpeed, normalLoad, requestedTorque, gripLimitedDriveTorque, ...
    lateralAcceleration, params)

    slipRatio = slipRatio(:).';
    integralState = integralState(:).';
    normalLoad = max(normalLoad(:).', 0);
    gripLimitedDriveTorque = gripLimitedDriveTorque(:).';
    gainSchedule = 1;

    targetSlipRatio = params.targetSlipRatio;
    slipError = targetSlipRatio - slipRatio;

    if params.useGripFeedforward
        availableFrictionCoefficient = max((params.tirePeakMuBase - ...
            params.tirePeakMuLoadSensitivity .* normalLoad) .* ...
            params.globalGripScale .* params.tireGripScaleByWheel, 0.1);
        if params.useFrictionEllipse
            lateralFrictionUsage = min(abs(lateralAcceleration) / ...
                params.gravity ./ availableFrictionCoefficient, 1);
            longitudinalFrictionAvailability = sqrt(max(1 - ...
                lateralFrictionUsage.^2, 0));
        else
            longitudinalFrictionAvailability = ones(1, 4);
        end

        feedforwardTireForce = (availableFrictionCoefficient .* ...
            longitudinalFrictionAvailability) .* normalLoad .* ...
            sin(params.tireMagicFormulaC * atan( ...
            params.tireMagicFormulaB * targetSlipRatio));
        feedforwardTorque = feedforwardTireForce .* params.wheelRadius ...
            ./ (params.gearRatio * params.drivetrainEfficiency);
    else
        feedforwardTorque = zeros(1, 4);
    end

    proportionalTorque = params.slipProportionalGain .* slipError;
    unlimitedTorqueCommand = feedforwardTorque + proportionalTorque + integralState;

    motorSpeed = max(abs(vehicleSpeed) / params.wheelRadius * ...
        params.gearRatio, 1);
    usablePowerPerMotor = min(params.peakMotorPowerPerMotor, ...
        params.vehiclePowerLimit / 4);
    motorDriveTorqueLimit = min(params.peakMotorTorque, ...
        usablePowerPerMotor ./ motorSpeed);

    maximumAllowedTorque = min(max(requestedTorque, 0), ...
        min(motorDriveTorqueLimit, gripLimitedDriveTorque));
    commandedMotorTorque = min(max(unlimitedTorqueCommand, 0), ...
        maximumAllowedTorque);

    integralStateRate = params.slipIntegralGain .* slipError + ...
        params.antiWindupGain .* ...
        (commandedMotorTorque - unlimitedTorqueCommand);
end
