function longitudinalTireForce = tire_long(slipRatio, normalLoad, ...
    lateralAcceleration, params)

    slipRatio = slipRatio(:).';
    normalLoad = max(normalLoad(:).', 0);

    availableFrictionCoefficient = max((params.tirePeakMuBase - ...
        params.tirePeakMuLoadSensitivity .* normalLoad) .* ...
        params.globalGripScale .* params.tireGripScaleByWheel, 0.1);

    if params.useFrictionEllipse
        lateralFrictionUsage = min(abs(lateralAcceleration) / params.gravity ...
            ./ availableFrictionCoefficient, 1);
        longitudinalFrictionAvailability = sqrt(max(1 - ...
            lateralFrictionUsage.^2, 0));
    else
        longitudinalFrictionAvailability = ones(1, 4);
    end

    longitudinalTireForce = (availableFrictionCoefficient .* ...
        longitudinalFrictionAvailability) .* normalLoad .* ...
        sin(params.tireMagicFormulaC .* atan( ...
        params.tireMagicFormulaB .* slipRatio));
end
